const SearchData = [
    {
      id: 1,
      categ: "Marketing head",
      ago: "1 week ago",
      state: "United states(Hybrid)",
      price: "$80k/yr-$100k/yr",
      button: "Applied",
    },
    {
      id: 2,
      categ: "Marketing head",
      ago: "1 week ago",
      state: "United states(Hybrid)",
      price: "$80k/yr-$100k/yr",
      button: "Applied",
    },
    {
      id: 3,
      categ: "Brand Designer",
      ago: "1 week ago",
      state: "United states(Hybrid)",
      price: "$80k/yr-$100k/yr",
      button: "Apply Now",
    },
    {
      id: 4,
      categ: "Brand Designer",
      ago: "1 week ago",
      state: "United states(Hybrid)",
      price: "$80k/yr-$100k/yr",
      button: "Apply Now",
    },
    {
      id: 5,
      categ: "Brand Designer",
      ago: "1 week ago",
      state: "United states(Hybrid)",
      price: "$80k/yr-$100k/yr",
      button: "Apply Now",
    },
    {
      id: 6,
      categ: "Brand Designer",
      ago: "1 week ago",
      state: "United states(Hybrid)",
      price: "$80k/yr-$100k/yr",
      button: "Apply Now",
    },
  ];